### DISCUSSION TITLE
How to migrate property name to a new name?

### DISCUSSION THREAD

**Discussion by eric-creekside** [xvik/yaml-updater#141] [Q&A]
Is it possible to use yaml-updater to migrate a specific property name to a new name, using the same value as the existing YAML has?

For example, old YAML structure is like this:
```yaml
app:
  propA: foo
```
New desired structure:
```yaml
app:
  props:
    a: foo
```

I tried using the variable syntax to place the value of the old property into the new property, like this:
```yaml
app:
  props:
    a: #{app.propA}
```

But that didn't work, the variable didn't get replaced with the original value.
