### ISSUE TITLE
Having some trouble merging yaml, it just says not changed.

### ISSUE THREAD

**Issue by TJM** [xvik/yaml-updater#8]
I created a docker container with the following Dockerfile:

```dockerfile
FROM openjdk:18-jdk-alpine3.13
# ADD some needed tools
RUN apk add --no-cache git openssh-client jq bash curl ca-certificates

# Install yaml-config-updater
ARG VERSION=1.3.2\
RUN cd /usr/local/bin \
  && curl -LO https://repo1.maven.org/maven2/ru/vyarus/yaml-config-updater-cli/${VERSION}/yaml-config-updater-cli-${VERSION}-all.jar \
  && ln -s yaml-config-updater-cli-${VERSION}-all.jar yaml-config-updater.jar

CMD ["java", "-jar", "/usr/local/bin/yaml-config-updater.jar", "--help"]
```

Original yaml: (mostly, I (CENSORED) the secrets that shouldn't be there anyhow.

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sdlc-pa-test
  namespace: pa-test
spec:
  releaseName: sdlc-pa-test
  chart:
    repository: https://artifactory.company.com/artifactory/company-helm
    name: patching-automation
    version: 0.9.0
  values:
    initContainerImage: docker-remote.artifactory.company.com/alpine:3.12
    replicaCount: 2
    image:
      tag: feat_puppet-jobs # override v0.9.0 with unreleased tag
      pullPolicy: Always

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/affinity: cookie
        nginx.ingress.kubernetes.io/affinity-mode: persistent
        nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
        nginx.ingress.kubernetes.io/configuration-snippet: | # Due to Citrix LB handling https
          more_set_input_headers "X-Forwarded-Proto: https";
          more_set_input_headers "X-Forwarded-Port: 443";
      hosts:
        - host: sdlc-pa-test.company.com
          paths: [ "/" ]

    # Database
    postgresql:
      postgresqlPassword: (CENSORED)
      image:
        registry: docker-remote.artifactory.company.com
      persistence:
        size: 5Gi

    extraEnvironmentVariables:
      - name: TRELLO_TOKEN
        value: (CENSORED) # me
      - name: OIDC_CLIENT_ID
        value: (CENSORED)
      - name: OIDC_CLIENT_SECRET
        value: (CENSORED)
      - name: OIDC_REDIRECT_URL
        value: https://sdlc-pa-test.company.com/auth/google/callback
      - name: OIDC_ISSUER_URL
        value: https://accounts.google.com
```

* update.yaml
```yaml
spec:
  values:
    image:
      tag: a95c9959
```

Debug output:

```
Updating configuration: /flux-sbx-apps/den3sbx/releases/pa-test/helmrelease-patching-automation.yaml
[main] DEBUG ru.vyarus.yaml.updater.YamlUpdater - Parsing new configuration...
[main] DEBUG ru.vyarus.yaml.updater.update.EnvSupport - Replacing variables in format '#{name}' from:
    PATH=/opt/openjdk-18/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    JAVA_HOME=/opt/openjdk-18
    OLDPWD=/flux-sbx-apps/den3sbx
    TERM=xterm
    SSH_AUTH_SOCK=/tmp/ssh-Ws5N4Ez2mZIR/agent.7
    SSH_AGENT_PID=8
    HOSTNAME=a232cb7b2894
    LD_LIBRARY_PATH=/opt/openjdk-18/lib/server:/opt/openjdk-18/lib:/opt/openjdk-18/../lib
    JAVA_VERSION=18-ea+11
    PWD=/flux-sbx-apps
    SHLVL=1
    HOME=/root
    _=/opt/openjdk-18/bin/java
[main] INFO ru.vyarus.yaml.updater.YamlUpdater - Environment variables applied to new config
[main] INFO ru.vyarus.yaml.updater.YamlUpdater - New configuration parsed (47 bytes, 4 lines)
[main] DEBUG ru.vyarus.yaml.updater.YamlUpdater - Parsing current configuration file (/flux-sbx-apps/den3sbx/releases/pa-test/helmrelease-patching-automation.yaml)...
[main] INFO ru.vyarus.yaml.updater.YamlUpdater - Current configuration parsed (1743 bytes, 51 lines)
[main] DEBUG ru.vyarus.yaml.updater.YamlUpdater - Merging configurations...
[main] INFO ru.vyarus.yaml.updater.YamlUpdater - Configuration merged
[main] DEBUG ru.vyarus.yaml.updater.YamlUpdater - Validating merged result
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/ingress/hosts[0] in current file
[main] DEBUG ru.vyarus.yaml.updater.update.ListMatcher - List item spec/values/ingress/hosts[0] match found: spec/values/ingress/hosts[0] (by 2 matches)
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/ingress/hosts[0] in update file
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[0] in current file
[main] DEBUG ru.vyarus.yaml.updater.update.ListMatcher - List item spec/values/extraEnvironmentVariables[0] match found: spec/values/extraEnvironmentVariables[0] (by 2 matches)
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[0] in update file
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[1] in current file
[main] DEBUG ru.vyarus.yaml.updater.update.ListMatcher - List item spec/values/extraEnvironmentVariables[1] match found: spec/values/extraEnvironmentVariables[1] (by 2 matches)
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[1] in update file
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[2] in current file
[main] DEBUG ru.vyarus.yaml.updater.update.ListMatcher - List item spec/values/extraEnvironmentVariables[2] match found: spec/values/extraEnvironmentVariables[2] (by 2 matches)
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[2] in update file
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[3] in current file
[main] DEBUG ru.vyarus.yaml.updater.update.ListMatcher - List item spec/values/extraEnvironmentVariables[3] match found: spec/values/extraEnvironmentVariables[3] (by 2 matches)
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[3] in update file
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[4] in current file
[main] DEBUG ru.vyarus.yaml.updater.update.ListMatcher - List item spec/values/extraEnvironmentVariables[4] match found: spec/values/extraEnvironmentVariables[4] (by 2 matches)
[main] DEBUG ru.vyarus.yaml.updater.update.UpdateResultValidator - Searching list item spec/values/extraEnvironmentVariables[4] in update file
[main] INFO ru.vyarus.yaml.updater.YamlUpdater - Merged file correctness validated
[main] INFO ru.vyarus.yaml.updater.YamlUpdater - Configuration not changed: /flux-sbx-apps/den3sbx/releases/pa-test/helmrelease-patching-automation.yaml

Configuration: /flux-sbx-apps/den3sbx/releases/pa-test/helmrelease-patching-automation.yaml (1743 bytes, 51 lines)

	Not changed
```

I am not sure why it is not updating the spec.values.image.tag ? Can you point me in the right direction?

Thanks in advance,
Tommy
